export default function ShockWavesPage() {
  return (
    <main>
      <h1>Shock Waves</h1>
      <p>
        Shock waves are a type of propagating disturbance. They are formed when
        a pressure wave is generated by a sudden change in pressure, such as an
        explosion or a sonic boom. Shock waves can travel faster than the speed
        of sound, and they can be very destructive. They are used in a variety
        of applications, including medical imaging, industrial processes, and
        military weapons.
      </p>
    </main>
  );
}
